<script setup>
import {computed,reactive,ref,watch} from 'vue'
const KEY='house-hunter-records-v1'
const amapKey=import.meta.env.VITE_AMAP_KEY||''
const demo=[{id:crypto.randomUUID(),title:'阳光花园 · 朝南一居室',rent:4200,payment:'押一付三',layout:'1室1厅',area:48,status:'considering',address:'上海市徐汇区斜土路街道',longitude:121.4562,latitude:31.1938,contactName:'陈女士',contactPhone:'138 0000 1234',description:'南向采光很好，客厅带阳台。地铁步行约 8 分钟，周边生活便利。需要确认晚上临街噪音。',images:[],createdAt:'2026-06-20T09:30:00Z',updatedAt:'2026-06-22T13:20:00Z'},{id:crypto.randomUUID(),title:'梧桐公寓 · 精装两居',rent:5800,payment:'押一付一',layout:'2室1厅',area:67,status:'favorite',address:'上海市长宁区江苏路附近',longitude:121.4304,latitude:31.2202,contactName:'王先生',contactPhone:'186 0000 5678',description:'装修新，收纳空间充足，小区安静。房东直租，可商量入住时间。',images:[],createdAt:'2026-06-18T06:10:00Z',updatedAt:'2026-06-21T10:05:00Z'}]
const blank=()=>({title:'',rent:'',payment:'押一付三',layout:'',area:'',status:'considering',address:'',longitude:'',latitude:'',contactName:'',contactPhone:'',description:'',images:[]})
const meta={considering:['考虑中','orange'],favorite:['很喜欢','green'],rejected:['已排除','gray'],rented:['已租下','blue']}
const load=()=>{try{return JSON.parse(localStorage.getItem(KEY))||demo}catch{return demo}}
const records=ref(load()),query=ref(''),filter=ref('all'),sort=ref('updated'),formOpen=ref(false),detailOpen=ref(false),editing=ref(''),selected=ref(),toast=ref(''),imageInput=ref(),quickPhotoInput=ref(),locationState=ref('')
const form=reactive(blank());let toastTimer
watch(records,v=>localStorage.setItem(KEY,JSON.stringify(v)),{deep:true})
const list=computed(()=>{let q=query.value.trim().toLowerCase();return records.value.filter(r=>(filter.value==='all'||r.status===filter.value)&&(!q||[r.title,r.address,r.description,r.contactName].some(x=>String(x||'').toLowerCase().includes(q)))).sort((a,b)=>sort.value==='rent'?(Number(a.rent)||Infinity)-(Number(b.rent)||Infinity):new Date(b.updatedAt)-new Date(a.updatedAt))})
const priced=computed(()=>records.value.filter(r=>Number(r.rent)>0))
const stats=computed(()=>({all:records.value.length,pending:records.value.filter(r=>r.status==='considering').length,fav:records.value.filter(r=>r.status==='favorite').length,avg:priced.value.length?Math.round(priced.value.reduce((n,r)=>n+Number(r.rent),0)/priced.value.length):0}))
const fmt=v=>new Intl.DateTimeFormat('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v))
function notify(t){toast.value=t;clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.value='',2200)}
function openCreate(){Object.assign(form,blank());editing.value='';locationState.value=amapKey?'点击定位按钮获取当前位置':'未配置高德地图 Key，可手动填写位置信息';formOpen.value=true}
function openEdit(r){Object.assign(form,blank(),JSON.parse(JSON.stringify(r)));editing.value=r.id;detailOpen.value=false;formOpen.value=true}
function save(){if(!form.title.trim())return notify('请填写房源名称');let now=new Date().toISOString(),data={...JSON.parse(JSON.stringify(form)),rent:form.rent?Number(form.rent):'',area:form.area?Number(form.area):'',longitude:form.longitude?Number(form.longitude):'',latitude:form.latitude?Number(form.latitude):'',updatedAt:now};if(editing.value){let i=records.value.findIndex(r=>r.id===editing.value);records.value[i]={...records.value[i],...data};notify('记录已更新')}else{records.value.unshift({...data,id:crypto.randomUUID(),createdAt:now});notify('看房记录已添加')}formOpen.value=false}
function remove(r){if(!confirm('确定删除“'+r.title+'”吗？此操作无法撤销。'))return;records.value=records.value.filter(x=>x.id!==r.id);detailOpen.value=false;notify('记录已删除')}
async function addImages(e){let files=[...e.target.files];if(form.images.length+files.length>8)return notify('每条记录最多添加 8 张图片');for(let f of files)if(f.type.startsWith('image/'))form.images.push(await compress(f));e.target.value=''}
async function quickAddPhotos(e){let files=[...e.target.files].filter(f=>f.type.startsWith('image/'));e.target.value='';if(!files.length)return notify('请选择房源照片');let limited=files.slice(0,8),images=[];for(let f of limited)images.push(await compress(f));let now=new Date(),iso=now.toISOString(),title='拍照记录 '+new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(now);records.value.unshift({...blank(),id:crypto.randomUUID(),title,images,createdAt:iso,updatedAt:iso});notify(files.length>8?'已创建记录，最多保存 8 张照片':'已通过照片创建记录')}
function compress(file){return new Promise((ok,no)=>{let rd=new FileReader();rd.onerror=no;rd.onload=()=>{let im=new Image();im.onerror=no;im.onload=()=>{let s=Math.min(1,1440/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=im.width*s;c.height=im.height*s;c.getContext('2d').drawImage(im,0,0,c.width,c.height);ok(c.toDataURL('image/jpeg',.76))};im.src=rd.result};rd.readAsDataURL(file)})}
function locate(){if(!navigator.geolocation)return notify('浏览器不支持定位');locationState.value='正在获取当前位置…';navigator.geolocation.getCurrentPosition(async({coords})=>{form.longitude=coords.longitude.toFixed(6);form.latitude=coords.latitude.toFixed(6);locationState.value='定位成功';if(amapKey)await reverseGeocode(form.longitude,form.latitude)},()=>locationState.value='定位失败，请允许位置权限或手动填写',{enableHighAccuracy:true,timeout:10000})}
async function reverseGeocode(lng,lat){try{let u='https://restapi.amap.com/v3/geocode/regeo?key='+amapKey+'&location='+lng+','+lat+'&extensions=base';let r=await fetch(u),d=await r.json();if(d.status==='1')form.address=d.regeocode.formatted_address}catch{locationState.value='已获取坐标，地址解析失败'}}
</script>

<template>
<div class="app">
<header class="top"><a class="brand"><b>⌂</b><span><strong>归巢</strong><small>我的看房记录</small></span></a><div class="head-actions"><label class="search">⌕<input v-model="query" placeholder="搜索小区、地址或联系人"><kbd>⌘ K</kbd></label><button class="soft photo-action" @click="quickPhotoInput.click()">▣ 拍照添加</button><button class="primary" @click="openCreate">＋ 添加看房记录</button></div></header><input ref="quickPhotoInput" hidden type="file" accept="image/*" multiple @change="quickAddPhotos">
<main>
<section class="intro"><div><p class="eyebrow">HOUSE HUNTING LOG</p><h1>找到那个让你想回家的地方。</h1><p>记录每一次看房，留住细节，做出更好的选择。</p></div><div class="mobile-actions"><button class="mobile-photo" @click="quickPhotoInput.click()">▣</button><button class="mobile-add" @click="openCreate">＋</button></div></section>
<section class="stats"><article><i class="lilac">⌂</i><div><small>全部看房</small><strong>{{stats.all}}</strong><em>处房源</em></div></article><article><i class="peach">◷</i><div><small>考虑中</small><strong>{{stats.pending}}</strong><em>处房源</em></div></article><article><i class="mint">♡</i><div><small>很喜欢</small><strong>{{stats.fav}}</strong><em>处房源</em></div></article><article><i class="sky">¥</i><div><small>平均租金</small><strong>{{stats.avg.toLocaleString()}}</strong><em>元/月</em></div></article></section>
<section class="content-head"><div><h2>看房记录</h2><p>共 {{list.length}} 条记录</p></div><div class="filters"><select v-model="filter"><option value="all">全部状态</option><option value="considering">考虑中</option><option value="favorite">很喜欢</option><option value="rejected">已排除</option><option value="rented">已租下</option></select><select v-model="sort"><option value="updated">最近更新</option><option value="rent">租金从低到高</option></select></div></section>
<section v-if="list.length" class="grid"><article v-for="r in list" :key="r.id" class="card" @click="selected=r;detailOpen=true"><div class="cover"><img v-if="r.images?.length" :src="r.images[0]"><div v-else class="placeholder"><b>⌂</b><small>等待添加房源照片</small></div><span class="status" :class="meta[r.status][1]">{{meta[r.status][0]}}</span><span v-if="r.images?.length>1" class="photos">▣ {{r.images.length}}</span></div><div class="body"><div class="title"><h3>{{r.title}}</h3><button @click.stop="openEdit(r)">•••</button></div><p class="address">⌖ {{r.address||'地址待补全'}}</p><div class="chips"><span v-if="r.layout">{{r.layout}}</span><span v-if="r.area">{{r.area}}㎡</span><span>{{r.payment}}</span></div><div class="bottom"><div class="price"><b v-if="r.rent">¥{{Number(r.rent).toLocaleString()}}</b><b v-else>待补全</b><small v-if="r.rent">/月</small></div><time>{{fmt(r.updatedAt)}} 更新</time></div></div></article></section>
<section v-else class="empty"><b>⌂</b><h3>还没有符合条件的记录</h3><p>调整筛选条件，或记录下一次看房。</p><button class="primary" @click="openCreate">＋ 添加看房记录</button></section>
</main>
<div v-if="formOpen" class="overlay" @mousedown.self="formOpen=false"><form class="modal form-modal" @submit.prevent="save"><header><div><p class="eyebrow">PROPERTY NOTE</p><h2>{{editing?'编辑看房记录':'添加看房记录'}}</h2></div><button type="button" class="close" @click="formOpen=false">×</button></header><div class="scroll">
<section class="form-section"><h3><i>1</i> 基本信息</h3><label class="full"><span>房源名称 *</span><input v-model="form.title" placeholder="例：梧桐公寓 · 精装两居"></label><div class="form-grid three"><label><span>月租金</span><input v-model="form.rent" type="number" min="0" placeholder="4500"></label><label><span>付款方式</span><select v-model="form.payment"><option>押一付一</option><option>押一付三</option><option>押二付一</option><option>半年付</option><option>年付</option></select></label><label><span>状态</span><select v-model="form.status"><option value="considering">考虑中</option><option value="favorite">很喜欢</option><option value="rejected">已排除</option><option value="rented">已租下</option></select></label><label><span>户型</span><input v-model="form.layout" list="layout-options" placeholder="选择或输入户型"><datalist id="layout-options"><option value="开间"></option><option value="1室0厅"></option><option value="1室1厅"></option><option value="2室1厅"></option><option value="2室2厅"></option><option value="3室1厅"></option><option value="3室2厅"></option><option value="4室及以上"></option></datalist></label><label><span>面积（㎡）</span><input v-model="form.area" type="number" min="0" placeholder="65"></label></div></section>
<section class="form-section"><h3><i>2</i> 图片</h3><div class="image-list"><div v-for="(im,i) in form.images" :key="im" class="thumb"><img :src="im"><button type="button" @click="form.images.splice(i,1)">×</button></div><button v-if="form.images.length<8" type="button" class="upload" @click="imageInput.click()"><b>＋</b><span>添加图片</span><small>{{form.images.length}}/8</small></button></div><input ref="imageInput" hidden type="file" accept="image/*" multiple @change="addImages"></section>
<section class="form-section"><h3><i>3</i> 位置信息</h3><div class="location"><label><span>详细地址</span><input v-model="form.address" placeholder="输入地址或使用当前位置"></label><button type="button" class="soft" @click="locate">◎ 获取当前位置</button></div><p class="location-state">{{locationState}}</p><div class="map-fallback"><b>⌖</b><p>{{amapKey?'定位后自动解析高德地图地址':'配置高德地图 Key 后可自动解析地址'}}</p><small>地址与经纬度始终可以手动修改</small></div><div class="form-grid two compact"><label><span>经度</span><input v-model="form.longitude" placeholder="121.473701"></label><label><span>纬度</span><input v-model="form.latitude" placeholder="31.230416"></label></div></section>
<section class="form-section"><h3><i>4</i> 联系与备注</h3><div class="form-grid two"><label><span>联系人</span><input v-model="form.contactName" placeholder="姓名或称呼"></label><label><span>联系电话</span><input v-model="form.contactPhone" placeholder="手机或微信号"></label></div><label class="full note"><span>看房描述</span><textarea v-model="form.description" rows="5" placeholder="记录采光、噪音、交通、周边设施、需要确认的问题……"></textarea></label></section>
</div><footer><button type="button" class="ghost" @click="formOpen=false">取消</button><button class="primary">{{editing?'保存修改':'保存记录'}}</button></footer></form></div>
<div v-if="detailOpen&&selected" class="overlay" @mousedown.self="detailOpen=false"><article class="modal detail"><button class="close floating" @click="detailOpen=false">×</button><div class="detail-hero"><img v-if="selected.images?.length" :src="selected.images[0]"><div v-else class="placeholder"><b>⌂</b></div></div><div class="detail-content"><span class="status static" :class="meta[selected.status][1]">{{meta[selected.status][0]}}</span><h2>{{selected.title}}</h2><p class="address">⌖ {{selected.address||'地址待补全'}}</p><div class="detail-price"><b v-if="selected.rent">¥{{Number(selected.rent).toLocaleString()}}</b><b v-else>待补全</b><span>{{selected.rent?'/月 · ':'待填写租金 · '}}{{selected.payment}}</span></div><div class="facts"><div><small>户型</small><b>{{selected.layout||'—'}}</b></div><div><small>面积</small><b>{{selected.area?selected.area+'㎡':'—'}}</b></div><div><small>联系人</small><b>{{selected.contactName||'—'}}</b></div></div><section><h3>看房笔记</h3><p>{{selected.description||'暂未添加描述。'}}</p></section><section v-if="selected.contactPhone"><h3>联系方式</h3><a :href="'tel:'+selected.contactPhone">☎ {{selected.contactPhone}}</a></section><p class="timestamps">创建于 {{fmt(selected.createdAt)}} · 更新于 {{fmt(selected.updatedAt)}}</p><div class="detail-actions"><button class="danger" @click="remove(selected)">删除</button><button class="primary" @click="openEdit(selected)">编辑记录</button></div></div></article></div>
<Transition name="toast"><div v-if="toast" class="toast">✓ {{toast}}</div></Transition>
</div>
</template>

